[package]
name = "i3-alternate-focus"
version = "0.2.5"
authors = ["lbonn", "ayosec"]
description = "Focus last window on i3"
license = "MIT"
repository = "https://github.com/ayosec/i3-focus-last"
edition = "2021"

[dependencies]
i3ipc = "0.10.0"
xcb = "1.4.0"
